name: Get image tag
description: Get image tag
inputs:
  branch:
    description: Branch
    required: true
  dev-tag-format:
    description: Format for dev tag
    required: false
    default: dev-:branch
outputs:
  tag:
    description: Image tag
    value: ${{ steps.get-tag.outputs.tag }}
runs:
  using: composite
  steps:
    - id: get-tag
      run: |
        if [ "${{ inputs.branch }}" == "latest" ]
        then
          echo "::set-output name=tag::latest"
        elif [ ${{ startsWith(inputs.branch, 'v') }} == true ]
        then
          tag=`echo "${{ inputs.branch }}" | sed "s/^v/""/"`
          echo "::set-output name=tag::$tag"
        else
          branch="${{ inputs.branch }}"
          tag=$(echo "${{ inputs.dev-tag-format }}" | sed "s|:branch|${branch}|g")
          echo "::set-output name=tag::$tag"
        fi
      shell: bash